### ISSUE TITLE
t.plan() does not work as should(at least on my platform: linux)

### ISSUE THREAD

**Issue by alfredwesterveld** [Jam3/hihat#35]
I like this project a lot :+1:, but I think I have discovered a bug.
`t.plan()` does not work async. I don't know how to fix this in your source code(yet?). The test file below does not work in hihat(electron) on my platform?

The following test(tape) below does not work on my machine

**test.js:**
```javascript
var test = require('tape');

test('timing test 2', function (t) {
    t.timeoutAfter(1000)
    t.plan(2)
    t.equal(typeof Date.now, 'function');
    var start = Date.now();

    setTimeout(function () {
        console.log("dadsadasdsa")
        t.ok('fuck me')
    }, 100);
    t.ok(true)
});
```

The output from node below is how it should be.
**output from node:**
```
alfred@alfred-SATELLITE-C55-A-1ND:~/n/test/tapetest$ node test.js 
TAP version 13
# timing test 2
ok 1 should be equal
ok 2 (unnamed assert)
dadsadasdsa
ok 3 (unnamed assert)
not ok 4 plan != count
  ---
    operator: fail
    expected: 2
    actual:   3
    at: null._onTimeout (/home/alfred/n/test/tapetest/test.js:11:11)
  ...

1..4
# tests 4
# pass  3
# fail  1
```

But from hihat the input is incorrect.
**output from hihat.**

```javascript
alfred@alfred-SATELLITE-C55-A-1ND:~/wt/test$ hihat test2.js --print
TAP version 13
# timing test 2
ok 1 should be equal
ok 2 (unnamed assert)

1..2
# tests 2
# pass  2

# ok

dadsadasdsa
```

**Update: `t.end()` does also not work as expected? P.S: in example below I call `t.end()` twice. If you only call it once on end I guess you could use `t.end()`?**

I guess I could just not use t.plan(), but instead use t.end(), but I think this is a bug(at least in linux). Hope you know how to fix this or else update documentation maybe? Many thanks.

**Comment by alfredwesterveld** [comment]
t.end() does also not work as it should?

**test2.js**
```javascript
var test = require('tape');

test('testing plan', function (t) {
    t.timeoutAfter(1000)
    t.plan(2)
    t.equal(typeof Date.now, 'function');
    var start = Date.now();

    setTimeout(function () {
        console.log("dadsadasdsa")
        t.ok('fuck me')
    }, 100);
    t.ok(true)
});
```
**expected:**
```
TAP version 13
# testing plan
ok 1 should be equal
ok 2 (unnamed assert)
dadsadasdsa
ok 3 (unnamed assert)
not ok 4 plan != count
  ---
    operator: fail
    expected: 2
    actual:   3
    at: null._onTimeout (/home/alfred/n/test/tapetest/test.js:11:11)
  ...

1..4
# tests 4
# pass  3
# fail  1
```
**actual on hihat:**
```
alfred@alfred-SATELLITE-C55-A-1ND:~/wt/test$ hihat test2.js --print
TAP version 13
# testing plan
ok 1 should be equal
ok 2 (unnamed assert)

1..2
# tests 2
# pass  2

# ok

dadsadasdsa
```

**Comment by mattdesl** [comment]
Thanks. This seems to be an issue with [tape](https://www.npmjs.com/package/tape) when it's being run in a browser. I can reproduce the same issues with a local dev server ([budo](https://www.npmjs.com/package/budo)) without using hihat.

**Comment by alfredwesterveld** [comment]
@mattdesl. You are right. Tape in node does not work the same as in the browser. Thanks for looking at this so fast.
